#!/bin/bash

echo "🚀 TMS Application - Live Deployment Guide"
echo "=========================================="
echo ""
echo "Follow these steps to get your live URL:"
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}Step 1: Push to GitHub${NC}"
echo "----------------------"
echo "Repository: https://github.com/ssaxena2609/tms-app"
echo ""
echo "Run these commands:"
echo "  git push -u origin main"
echo ""
echo "If you get an authentication error, use a Personal Access Token:"
echo "  1. Go to: https://github.com/settings/tokens"
echo "  2. Generate new token (classic)"
echo "  3. Select 'repo' scope"
echo "  4. Copy the token"
echo "  5. Use it as password when pushing"
echo ""

echo -e "${BLUE}Step 2: Deploy Backend to Railway${NC}"
echo "---------------------------------"
echo "1. Go to: https://railway.app"
echo "2. Sign up with GitHub (free)"
echo "3. Click 'New Project'"
echo "4. Select 'Deploy from GitHub repo'"
echo "5. Choose: ssaxena2609/tms-app"
echo "6. Select 'backend' folder"
echo ""
echo "7. Add Environment Variables:"
echo "   PORT=4000"
echo "   NODE_ENV=production"
echo "   JWT_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")"
echo "   CORS_ORIGIN=https://your-app.vercel.app"
echo ""
echo "8. Deploy and COPY your Railway URL"
echo "   (e.g., https://tms-backend-production.up.railway.app)"
echo ""

echo -e "${BLUE}Step 3: Deploy Frontend to Vercel${NC}"
echo "----------------------------------"
echo "1. Go to: https://vercel.com"
echo "2. Sign up with GitHub (free)"
echo "3. Click 'New Project'"
echo "4. Import: ssaxena2609/tms-app"
echo "5. Configure:"
echo "   - Framework Preset: Vite"
echo "   - Root Directory: frontend"
echo "   - Build Command: npm run build"
echo "   - Output Directory: dist"
echo ""
echo "6. Add Environment Variable:"
echo "   VITE_GRAPHQL_URI=<YOUR_RAILWAY_URL>/graphql"
echo ""
echo "7. Deploy and GET YOUR LIVE URL!"
echo "   (e.g., https://tms-app.vercel.app)"
echo ""

echo -e "${BLUE}Step 4: Update CORS${NC}"
echo "-------------------"
echo "1. Go back to Railway dashboard"
echo "2. Find your backend project"
echo "3. Go to 'Variables'"
echo "4. Update CORS_ORIGIN to your Vercel URL"
echo "5. Redeploy"
echo ""

echo -e "${GREEN}✅ Done! Your app is live!${NC}"
echo ""
echo "Access your live app at your Vercel URL"
echo "Login with: admin@tms.com / admin123"
echo ""
echo "📚 For detailed instructions, see QUICK_DEPLOY.md"
