#!/bin/bash

echo "🚀 TMS Deployment Helper"
echo "========================"
echo ""
echo "This script will help you deploy your TMS application."
echo ""

# Check if git is initialized
if [ ! -d .git ]; then
    echo "📦 Initializing git repository..."
    git init
    git add .
    git commit -m "Complete TMS application with authentication"
fi

echo "✅ Git repository ready!"
echo ""
echo "📋 Next Steps:"
echo ""
echo "1️⃣  Create a GitHub repository:"
echo "   - Go to https://github.com/new"
echo "   - Create a new repository (e.g., 'tms-app')"
echo "   - Don't initialize with README"
echo ""
echo "2️⃣  Push your code to GitHub:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3️⃣  Deploy Backend to Railway:"
echo "   - Go to https://railway.app"
echo "   - Click 'New Project' → 'Deploy from GitHub repo'"
echo "   - Select 'backend' folder"
echo "   - Add these environment variables:"
echo "     PORT=4000"
echo "     NODE_ENV=production"
echo "     JWT_SECRET=$(node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")"
echo "     CORS_ORIGIN=https://your-app.vercel.app"
echo ""
echo "4️⃣  Deploy Frontend to Vercel:"
echo "   - Go to https://vercel.com"
echo "   - Click 'New Project' → Import your repository"
echo "   - Framework: Vite"
echo "   - Root Directory: frontend"
echo "   - Add environment variable:"
echo "     VITE_GRAPHQL_URI=https://your-backend.railway.app/graphql"
echo ""
echo "5️⃣  Update CORS:"
echo "   - Go back to Railway dashboard"
echo "   - Update CORS_ORIGIN to your Vercel URL"
echo "   - Redeploy"
echo ""
echo "🎉 Your app will be live!"
echo ""
echo "📚 For detailed instructions, see:"
echo "   - QUICK_DEPLOY.md"
echo "   - DEPLOYMENT.md"
echo ""
